// Generated by CoffeeScript 1.8.0
(function() {
  var barista, hasMilk, makeCoffee;

  hasMilk = function(style) {
    switch (style) {
      case "latte":
      case "cappuccino":
        return true;
      default:
        return false;
    }
  };

  makeCoffee = function(style) {
    return style || 'Espresso';
  };

  barista = function(style) {
    var coffee, now, time;
    now = new Date();
    time = now.getHours();
    if (hasMilk(style) && time > 12) {
      return "No!";
    } else {
      coffee = makeCoffee(style);
      return "Enjoy your " + coffee + "!";
    }
  };

  barista("latte");

}).call(this);
